name: Archive PR Files

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        default: '1'

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch pull request files
        id: fetch_files
        run: |
          pr_number=${{ github.event.inputs.pr_number }}
          dir_name=release_resources
          mkdir -p $dir_name
          echo "dir_name=$dir_name" >> $GITHUB_ENV
          git fetch origin pull/$pr_number/head:pr-$pr_number
          git diff --name-only --diff-filter=A origin/develop pr-$pr_number > $dir_name/added_files.txt
          git diff --name-only --diff-filter=M origin/develop pr-$pr_number > $dir_name/modified_files.txt
          git diff --name-only --diff-filter=D origin/develop pr-$pr_number > $dir_name/deleted_files.txt

      - name: added files
        run: |
          dir_name=${{ env.dir_name }}
          child_dir_name=$dir_name/added_files
          mkdir -p $child_dir_name
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              mkdir -p "$(dirname "$child_dir_name/$file")"
              cp "$file" "added_files/$file"
            fi
          done < $dir_name/added_files.txt

      - name: modified files
        run: |
          dir_name=${{ env.dir_name }}
          child_dir_name=$dir_name/modified_files
          mkdir -p $child_dir_name
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              mkdir -p "$(dirname "$child_dir_name/$file")"
              cp "$file" "modified_files/$file"
            fi
          done < $dir_name/modified_files.txt

      - name: Fetch pull request branch name
        id: get_branch
        run: |
          pr_number=${{ github.event.inputs.pr_number }}
          branch_name=$(gh pr view $pr_number --json headRefName -q .headRefName)
          branch_name_escaped=$(echo "$branch_name" | sed 's|/|_|g')
          echo "branch_name=$branch_name" >> $GITHUB_ENV
          echo "branch_name_escaped=$branch_name_escaped" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr#${{ github.event.inputs.pr_number }}-${{ env.branch_name_escaped }}
          path: ${{ env.dir_name }}/
